name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: App Build
        run: npm run build

      - name: Run tests and generate HTML report
        run: npx vitest run --reporter=default --reporter=html --outputFile=./test-results/index.html

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./test-results/index.html

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist

  show-test-artifact:
    needs: build-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Test Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: test-report
          path: downloaded-test-report

      - name: Show Test Report Content
        run: |
          echo "Test report contents:"
          ls -la downloaded-test-report
          cat downloaded-test-report/index.html || echo "No test report found"

  deploy:
    needs: show-test-artifact
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Run the app
        run: npm run start